### ISSUE TITLE
Implement Tacos

### ISSUE THREAD

**Issue by Zbob750** [Thinkofname/steven#52]
See title.

A major feature is missing from Vanilla. That is, of course, taco item, block, and entity support. Adding it will make steven a unique part of the client community and I urge you to work towards full taco support as soon as possible.

**Comment by Techcable** [comment]
**THIS IS NOT  JUST FOR MACS**
THIS IS FOR ALL OPERATING SYSTEMS EXCEPT WINDOWS AND DEBIAN!

**Comment by TheUnnamedDude** [comment]
@Techcable I've addressed your concern.

**Comment by Techcable** [comment]
@TheUnnamedDude Linux is the only program you need to use on your computer. Your computer is only a bootloader for Linux. The best programmers use Linux, there's no reason not to use it. Everyone who says otherwise has not truly utilized Linux to its full extent, along with its glorious plugin system.
