### ISSUE TITLE
collision-rs no longer exists

### ISSUE THREAD

**Issue by hcorion** [Thinkofname/steven#66]
Hi, 
I was trying to compile steven on msys2 because I use steven to test if the rustc package works, and collision-rs no longer exists. It is supposed to be here: https://github.com/csherratt/collision-rs but that page no longer exists, in fact the GitHub user no longer exists. This seems to be a fork of it: https://github.com/erickt/collision-rs but I'm not sure how up to date it is and it doesn't have a cargo.toml.

**Comment by Thinkofname** [comment]
Thats a shame, wonder what happened to it. That other repo is so old it pre-dates cargo and I didn't keep a fork of the original collision-rs repo (I really should have).

You may be able to get it to build by replacing 
```toml
collision = {git = "https://github.com/csherratt/collision-rs", rev = "f80825e"}
```
with
```toml
collision = "0.9.0"
```
In Cargo.toml.

I don't maintain this anymore due to not having the time sadly so if that doesn't work you are on your own.

**Comment by hcorion** [comment]
Thanks @TheUnnamedDude !
